[package]
name = "table-rustractor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
scraper = "0.20"
reqwest = { version = "0.12" }
tokio = { version = "1.40", features = ["full"] }
csv = "1.3"
anyhow = "1.0"
colored = "2.1"
